export const GAMEOPTIONS = {
  quizType: 'Wassce',
  subject: 'Physics',
  year: 'May/June 2022',
  totalQues: 20,
  quesStyle: 'random',
  time: 2,
};

export const QUESTIONS = [
  {
    id: 1,
    quesNo: 1,
    topic: 3,
    question: 'How many sons did Jacob have?',
    quesImg: '',
    options: '12**14**9**3',
    ans: 'a',
  },
  {
    id: 2,
    quesNo: 2,
    topic: 2,
    question: 'What is the capital of France?',
    quesImg: '',
    options: 'Paris**Berlin**London**Rome',
    ans: 'a',
  },
  {
    id: 3,
    quesNo: 3,
    topic: 1,
    question: "Who wrote 'Romeo and Juliet'?",
    quesImg: '',
    options: 'Shakespeare**Dickens**Hemingway**Austen',
    ans: 'a',
  },
  {
    id: 4,
    quesNo: 4,
    topic: 4,
    question:
      'Which planet is known as the Red Planet uioejifjdjkdjhfjkfgjjdjhdjdrjhdjfdjdfjjdfjdfjhdfjhdfjhdfdfjhjhujhuuiiooiioioijkkjjjkkjjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkklkkkjjkjkjkjkjklkkjjkjkjkljkljkljklkjlkjlkjljkjkljkljkljkjklooouieruyeruyeryereuieuyeeruyuerereeuipoppoiopoioioiioiooioiioiooiiopopiippioiopiopyterjhejhjrjjhjjkjkjkjkjkjkjkjkkjjjjjjjjjjjjjjjjjjsdgdghhwgygyerygerygyeryeryeryreyeryeryertyty?',
    quesImg: '',
    options: 'Mars**Venus**Jupiter**Saturn',
    ans: 'a',
  },
  {
    id: 5,
    quesNo: 5,
    topic: 5,
    question: 'What is the largest mammal on Earth?',
    quesImg: '',
    options: 'Blue Whale**Elephant**Giraffe**Hippopotamus',
    ans: 'a',
  },
  {
    id: 6,
    quesNo: 6,
    topic: 3,
    question: 'In which year did World War II end?',
    quesImg: '',
    options: '1945**1918**1939**1941',
    ans: 'a',
  },
  {
    id: 7,
    quesNo: 7,
    topic: 2,
    question: 'What is the currency of Japan?',
    quesImg: '',
    options: 'Yen**Won**Dollar**Euro',
    ans: 'a',
  },
  {
    id: 8,
    quesNo: 8,
    topic: 1,
    question: 'Who painted the Mona Lisa?',
    quesImg: '',
    options: 'Leonardo da Vinci**Vincent van Gogh**Pablo Picasso**Claude Monet',
    ans: 'a',
  },
  {
    id: 9,
    quesNo: 9,
    topic: 4,
    question: 'Which is the largest ocean on Earth?',
    quesImg: '',
    options: 'Pacific Ocean**Atlantic Ocean**Indian Ocean**Arctic Ocean',
    ans: 'a',
  },
  {
    id: 10,
    quesNo: 10,
    topic: 5,
    question: 'What is the fastest land animal?',
    quesImg: '',
    options: 'Cheetah**Lion**Gazelle**Leopard',
    ans: 'a',
  },
  // Add more questions as needed
];
